export enum Role {
  PLATFORM_ADMIN = 'PLATFORM_ADMIN',
  REGIONAL_SUPERVISOR = 'REGIONAL_SUPERVISOR',
  SCHOOL_ADMIN = 'SCHOOL_ADMIN',
  TEACHER = 'TEACHER',
  STUDENT = 'STUDENT',
  PARENT = 'PARENT',
}
